# wrangler.toml
name = 'house-of-shriya'
pages_build_output_dir = "dist"
compatibility_date = "2026-09-07"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
APP_NAME = "House of Shriya"
